### PR TITLE
Fix wrong opendir flag value in listing

### PR DESCRIPTION
**Pull request by didiez**

### CODE REVIEW

**Comment by ams-tschoening** [comment]
Could you please provide additional screenshots or description how exactly the problem looks like, e.g. simply before vs. after applying your fix? I wonder a bit why nobody recognized the wrong order before.

**Comment by didiez** [comment]
> Could you please provide additional screenshots or description how exactly the problem looks like, e.g. simply before vs. after applying your fix? I wonder a bit why nobody recognized the wrong order before.

Sure. This bug was hidden because the icon used for `dir` and `diropen` was the same in the default templates (see `templates/calm/directory.tmpl`):
```php
[websvn-defineicons]
dir=<img src="[websvn:locwebsvnhttp]/templates/calm/images/directory.png" alt="[DIRECTORY]" class="icon" />
diropen=<img src="[websvn:locwebsvnhttp]/templates/calm/images/directory.png" alt="[DIRECTORY]" class="icon" />
```
Changing the icon for the open folder to see the difference:
before | after
-----------|-----------
image | image

**Comment by ams-tschoening** [comment]
Thanks, that makes sense. Do you want to provide your changed icon as well?

**Comment by didiez** [comment]
The icon used in the screenshot was only to show the issue. I am not sure that is the right icon to represent an "open" folder. There is no `folder_open.png` in the silk iconset (used in `calm`). The one shown in the screenshot is `folder_go.png` 
http://www.famfamfam.com/lab/icons/silk/icons/folder_go.png

**Pull request merged**
