### PR TITLE
 Improve compatibility with paths and file names not encoded in UTF-8.

### LINKED ISSUE #105: The display and link will be corrupted, when the path/file name encoding is not UTF-8.
After changing these as follows, it seems to be working good.

comp.php
filedetails.php
log.php

```diff
--- a/comp.php
+++ b/comp.php
@@ -372,6 +372,7 @@
 
 				// Check for a new node entry
 				if (strncmp(trim($line), 'Index: ', 7) == 0) {
+					$line = mb_convert_encoding($line, 'UTF-8', 'auto');
 					// End the current node
 					if ($node) {
 						$listing[$index++]['endpath'] = true;
@@ -393,7 +394,7 @@
 					$listvar = &$listing[$index];
 					$listvar['newpath'] = escape($absnode);
 
-					$listvar['fileurl'] = $config->getURL($rep, $absnode, 'file').'rev='.$rev2;
+					$listvar['fileurl'] = $config->getURL($rep, toOutputEncoding($absnode), 'file').'rev='.$rev2;
 
 					if ($debug) echo 'Creating node '.$node.'<br />';
 
@@ -439,6 +440,7 @@
 
 						$node = $propnode;
 
+						$node = mb_convert_encoding($node, 'UTF-8', 'auto');
 						$listing[$index++]['newpath'] = $node;
 						clearVars();
 					}
```
```diff
--- a/filedetails.php
+++ b/filedetails.php
@@ -108,10 +108,10 @@
 
 	// If a MIME type is associated with the file, deliver with Content-Type header.
 	if ($history && !empty($mimeType) && $rep->hasReadAccess($path, false)) {
-		$base = basename($path);
+		$base = basename(urldecode($path));
 		header('Content-Type: '.$mimeType);
 		//header('Content-Length: '.$size);
-		header('Content-Disposition: inline; filename='.urlencode($base));
+		header('Content-Disposition: inline; filename="'.$base.'"; '."filename*=UTF-8''".rawurlencode($base));
 		$svnrep->getFileContents($path, '', $rev, $peg);
 		exit;
 	}
```
```diff
--- a/log.php
+++ b/log.php
@@ -307,7 +307,7 @@
 				$listvar['revlog'] = nl2br($bugtraq->replaceIDs(create_anchors(xml_entities($revision->msg))));
 				$listvar['rowparity'] = $row;
 
-				$listvar['compareurl'] = $config->getURL($rep, '', 'comp').'compare[]='.$rpath.'@'.($thisrev - 1).'&amp;compare[]='.$rpath.'@'.$thisrev;
+				$listvar['compareurl'] = $config->getURL($rep, '', 'comp').'compare[]='.urlencode($rpath).'@'.($thisrev - 1).'&amp;compare[]='.urlencode($rpath).'@'.$thisrev;
 
 				if ($showchanges) {
 					// Aggregate added/deleted/modified paths for display in table
```

### PR DESCRIPTION
**Pull request by ams-tschoening**
The download-header focuses on UTF-8 only by purpose, it's unnecessary difficult to maintain a backwards compatible file name and not necessary in current browsers anymore. https://tools.ietf.org/html/rfc6266#section-5

The second commit is to prevent the following warning:

> Notice:  iconv(): Detected an incomplete multibyte character in input string in [...]\include\command.php on line 34

Clipboard01

Tested things on Windows and that uses windows-1252 most likely. Not sure if that list-approach is good at all, because what's really needed is the default codepage of the current OS. Things look a bit difficult, though:

https://stackoverflow.com/questions/20408377/utf-8-characters-in-uploaded-file-name-are-jumbled-on-file-upload?noredirect=1&lq=1

@n0nel Please have a look an test things.

This fixes #105.

### CODE REVIEW

**Comment by n0nel** [comment]
@ams-tschoening , Thanks for making this pull request.
The patch to command.php causes character corruption. In my environment, there is no "Notice: iconv()" without applying the patch.
The other patches (comp.php, filedetails.php, log.php) are working fine.

**Comment by ams-tschoening** [comment]
How did you test exactly for `command.php`? Only with my changes or did you apply your own code pages like mentioned in the issue again or ...? That list-approach is broken by design, so please post the exact line you tested with.

If you DID NOT apply your code page-customizations, please test again with doing so 1. at the end of the list and if that doesn't work at the front of it. My changes were NOT designed to replace your changes, only to fix the notice I#m seeing with plain `windows-1252`. As your code pages aren't `windows-1252`, I would have expected that you need to put your own customizations back in place.

**Comment by n0nel** [comment]
I have been using this modification in the past.
`$list = array('UTF-8', 'SJIS', 'JIS', 'EUC-JP', 'ISO-8859-1');`

I tried it as shown in the patch, with the following modifications.
`$list = array('windows-1252', 'ISO-8859-1', 'UTF-8', 'SJIS', 'JIS', 'EUC-JP');`

It didn't work, so I reverted and used it.

**Comment by ams-tschoening** [comment]
What about the following?

    $list = array('SJIS', 'JIS', 'EUC-JP', 'windows-1252', 'ISO-8859-1', 'UTF-8');

**Comment by n0nel** [comment]
> 
> 
> What about the following?
> 
> ```
> $list = array('SJIS', 'JIS', 'EUC-JP', 'windows-1252', 'ISO-8859-1', 'UTF-8');
> ```

Unfortunately it doesn't work.

**Comment by michael-o** [comment]
Looking into...

**Comment by ams-tschoening** [comment]
This is what I get with my UTF-8 configured UB 18.04 and using `windows-1252` as the first item:

Clipboard01

Clipboard02

	LANG=en_US.UTF-8
	LANGUAGE=
	LC_CTYPE="en_US.UTF-8"
	LC_NUMERIC="en_US.UTF-8"
	LC_TIME="en_US.UTF-8"
	LC_COLLATE="en_US.UTF-8"
	LC_MONETARY="en_US.UTF-8"
	LC_MESSAGES="en_US.UTF-8"
	LC_PAPER="en_US.UTF-8"
	LC_NAME="en_US.UTF-8"
	LC_ADDRESS="en_US.UTF-8"
	LC_TELEPHONE="en_US.UTF-8"
	LC_MEASUREMENT="en_US.UTF-8"
	LC_IDENTIFICATION="en_US.UTF-8"
	LC_ALL=

Therefore I'm going to merge with that change for now, because `windows-1252` should make sense for many Windows-users. This needs to be reworked to some concept of using a "current code page" instead of a hard-coded list anyway at some point. @n0nel has a workaround for ones system as well, so shouldn't be a problem.

**Pull request merged**
