### PR TITLE
Remove bundled GeSHi

### PR DESCRIPTION
**Pull request by michael-o**
Use GeSHi from ports/packages rather than holding a local copy of it. Configure the path with setGeshiScriptPath().

### CODE REVIEW

**Comment by michael-o** [comment]
The big difference between Geshi and Archive_Tar/Text_Diff is that both are managed through PEAR which is autoregistered in the global `include_path` whereas Geshi is installed as is. In Debian/Ubuntu it is installed in `/usr/share/php-geshi` on my FreeBSD server in `/usr/local/lib/php/geshi`.

The `class_exists` is for the PEAR case only. The app doesn't have to know where PEAR packages reside, it only has to know that they can be loaded via `include_path` w/o any intervention.

I happily accept better approaches cross-platform.

**Comment by tschoening** [comment]
I see, Geshi is not available using PEAR by default. What do you think about the following:

> $ pear channel-discover pear.geshi.org
> $ pear install geshi/geshi

https://cweiske.de/tagebuch/geshi-pear-channel.htm
http://pear.geshi.org

This worked easily for me under UB 14.04 and provided version 1.0.9.0 as well. In my opinion would be more consistent with what is needed for Archive_Tar etc. already and we wouldn't need to manage the additional path.

**Comment by joubertredrat** [comment]
We can consider to use `composer` for provide GeSHi in this case?

https://packagist.org/packages/geshi/geshi

**Comment by michael-o** [comment]
@tschoening I love it. Just tried here on my FreeBSD server at work. I will change my PR.

**Comment by michael-o** [comment]
@tschoening Changed PR. Please review.

**Pull request merged**
