### PR TITLE
Adjusts for PHP 7.4

### PR DESCRIPTION
**Pull request by erickmajor**
Modifying curly brackets by square brackets, because in PHP 7.4 this resource is outdated.

### CODE REVIEW

**Comment by ams-tschoening** [comment]
Thanks for the patch! Some background for people like me not too up-to-date with the PHP-ecosystem. This doesn't read like it breaks anything in older releases of PHP, correct?

https://wiki.php.net/rfc/deprecate_curly_braces_array_access

One minor note for the patch, though: I would have preferred NOT introducing additional spaces, but might live with how it is now. Any opinions?

**Comment by michael-o** [comment]
Can we leave the formatting changes out? The patch reads confusing...

**Comment by michael-o** [comment]
@michael-o According to the source you provided this should have been deprecated a long time ago but has been pulled off. It seems to be a safe bet to accept. I will accept after the whitespace change is undone.

**Comment by erickmajor** [comment]
Hi guys,

I removed the spaces added by me in last commit.

Thanks by review.

**Pull request merged**
