### PR TITLE
Migrate PHP from 5.3 to 7.2

### PR DESCRIPTION
**Pull request by lkppo**
Update Geshi to 1.0.9.0 for PHP 7 support and migrate to support PHP from 5.3 to 7.2.

Signed-off-by: Stéphane Aulery <lkppo@free.fr>

### CODE REVIEW

**Comment by tschoening** [comment]
Using `__construct` is only supported by PHP version 5+, correct? So in `doc/install.html`, we need to additionally increment the needed version of PHP to `5.3.0` or some other 5? Would be great if you could change that as well.

Just for my understanding, those `foreach`-changes are code style and not strictly related to PHP 7 compatibility, correct? Because they are documented for PHP 4 already. It would be great if you could change those to `foreach (`, note the additional space, because in my opinion this is easier to read and has been used before.

@michael-o Do you care about the Geshi-changes now because in #8 you remove it? Shouldn't harm to merge them now and remove it later at your will in my opinion.

**Comment by michael-o** [comment]
@tschoening I would drop them because it is not our task to fix Geshi. Espcially because the bundled Geshi version is old. I have removed it and I would expect upstream devs to take care of PHP 7 compat.
Internally, I raised the minimum to 5.6 w/o enforcement because this is the only supported PHP version for now.

Regarding the rest, if it ain't broke, don't fix it. @lkppo Does PHP 7 issue a warning or an error for the current code? If so, I'd be reluctant to change before 2.4.

**Comment by michael-o** [comment]
@lkppo Thanks for the info. Please drop Geshi, the change is massive.

**Comment by joubertredrat** [comment]
I agree with @michael-o for drop Geshi. Make no sense to maintain a old lib.

About a minimal version, I think that is good to for set minimum PHP version to 5.6 because this release is last from 5 branch and will continue receiving security updates until December 2018.

While next version is in 5.6 we can refactor for PHP 7.X more calmly.

Reference:
http://php.net/supported-versions.php

**Comment by lkppo** [comment]
I updated my PR.

**Comment by michael-o** [comment]
Reviewing the newest commits:

The drop is incomplete. You simply deleted Geshi w/o making an external version pluggable. Like I did [here](https://sourceforge.net/u/michael-o/svn-enterprise-auth/72/). PR pending.

Can you rework (fixup) your PR to PHP changes only within one commit? Leaving out Geshi completely, because this should be a separate PR.

**Comment by lkppo** [comment]
No, I will not rework my PR because I'm not fluent with Git, and I will just mess around with it if I do that.

I don't understand why people are obsessed by the perfect commit log, but, If you want one commit, I drop it, and redo it all. It's just a 14 lines change.

**Comment by michael-o** [comment]
That approach is fine too.

**Comment by lkppo** [comment]
OK, let's go.

**Comment by tschoening** [comment]
@lkppo I'm sorry, but I think have broken things by accident. Let me have a look at this before you do anything new.

**Comment by tschoening** [comment]
Closing this in favour of PR #30, which is based on this and only contains the necessary changes currently.

**Pull request closed without merging**
