### PR TITLE
Fix access rights in a subpath repo

### PR DESCRIPTION
**Pull request by Tom-H-**
The subpath was not concatenated to the path at `Repository::hasReadAccess()` call. So WebSVN throw an error on all pages ("You do not have the necessary permissions to view this content.").

The second commit fix an error in SVN log parsing. In case of unauthorized path log, the subpath was checked even after the file log variable was unset.

### CODE REVIEW

**Comment by Tom-H-** [comment]
Your PR #69 is what I tried at first.
But as you can see in the parsing of SVN logs, the file paths are absolute with the root of the SVN server. So it's stupid to add the subpath to all the files since the subpath is allowed.
For example, you allow a/b/c and not a/b/d. All files a/b/d/x will be allowed because you will be testing a/b/c/a/b/d/x.

**Comment by ams-tschoening** [comment]
I would prefer not using the term `stupid` for a solution that seems to be the correct thing to do and from my understanding of your newest commits, simply didn't properly handle one exception from the rule. The problem seems to be that there's currently no clear distinction between paths containing the subpath and those not, but in my opinion, `has*Access` should deal with such things internally only.

If logging is currently the only exception from the rule, I suggest adding `hasLog[Read]Access` instead of additional arguments. That fits to the availability of `hasUnrestrictedReadAccess` and one could easier search for and document the purpose of such a function.

Maybe one decides one time to even simply check if the provided path to `has*Access` already starts with the subpath and prepend as necessary? The subpath-handling in `svnlook` after checking for read access should be reworked in the future as well to get removed, so that `svnlook` doesn't need to care for those details anymore.

Prepending the subpath itself should be an own function in my opinion as well. So I am updating my PR again and we simply let others decide which implementation they prefer. This way we don't lose anything.

**Comment by michael-o** [comment]
Does this change the behavior of current installation since the new boolean flag is set to `true`?

**Comment by ams-tschoening** [comment]
> Does this change the behaviour of current installation since the new boolean flag is set to true?

Formerly wrong behaviour is fixed, while formerly correct one is kept. That's the purpose of the flag, to distinguish those both cases. It's not about fixing vs. non-fixing at all.

**Comment by Tom-H-** [comment]
To be clear, the word "stupid" was not for you, but for `function hasReadAccess($path, $checkSubDirs = false) { return true; }`.. Sorry about that...

> Maybe one decides one time to even simply check if the provided path to `has*Access` already starts with the subpath and prepend as necessary?

Maybe I misunderstood, but I don't think it will work. A different root path will normally not be allowed. However, if you prepend the subpath, it comes back to the same problem of `return true`.



Since you have planned to remove subpath in svnlook, I think the choice between a function with a boolean argument or two functions is not important. So I'll let you merge/close these PR.

**Comment by ams-tschoening** [comment]
Not sure if subpath can be removed at all, because when I suggested that, I didn't have the main use case in mind: "Mounting" a sub directory of a repo as a pseudo-repo at the same top level like all other repos. This is something which authz and permissions itself can not do. In my opinion, this makes it even more important to improve and somewhat better distinguish the subpath handling. Therefore I'm going to merge my PR #69 instead of yours, I already resolved the conflicts there as well.

It would be great if you could test one more time if things work for you. Thanks!

**Pull request closed without merging**
