### PR TITLE
Remove redundant code

### PR DESCRIPTION
**Pull request by michael-o**

### CODE REVIEW

**Comment by michael-o** [comment]
That is true, but what if something else has to be added, e.g., some PHP 7.x quirks?

**Comment by tschoening** [comment]
With the same argument you could have left `$config' in as well. :-) But at least `execCommand` seems to already use some global state with `$tmp`, so simply let's keep it as is.

**Comment by michael-o** [comment]
@tschoening That was my bad. I failed to remove them when I removed the Windows quirks with PHP <5.3.0.

**Comment by michael-o** [comment]
Shall I merge this commit? I am not certain we have agreed on something.

**Comment by tschoening** [comment]
What's with the following line:

> return @exec($cmd, $tmp, $retcode);

Does `$tmp` needs to be removed or not? Besides that, merge it. Things can get removed later as well if not needed anymore.

**Comment by michael-o** [comment]
@tschoening I'll check.

**Comment by michael-o** [comment]
One cannot remove `$tmp`, but rather rename to `$output`. This simply satisfies the [contract of `exec()`](http://php.net/manual/de/function.exec.php). The command output is not evaluated somewhere. At best, we can add a comment there.

**Comment by tschoening** [comment]
Guten Tag Michael Osipov,
am Montag, 26. Februar 2018 um 13:13 schrieben Sie:

> One cannot remove $tmp, but rather rename to $output. This simply
> satisfies the contract of exec(). The command output is not
> evaluated somewhere. At best, we can add a comment there.

No need for a comment, I might simply have misunderstood at all.
Anyway, renaming $tmp to $output seems like a good idea, so please do
that and simply merge the PR afterwards.

Mit freundlichen Grüßen,

Thorsten Schöning

-- 
Thorsten Schöning       E-Mail: Thorsten.Schoening@AM-SoFT.de
AM-SoFT IT-Systeme      http://www.AM-SoFT.de/

Telefon...........05151-  9468- 55
Fax...............05151-  9468- 88
Mobil..............0178-8 9468- 04

AM-SoFT GmbH IT-Systeme, Brandenburger Str. 7c, 31789 Hameln
AG Hannover HRB 207 694 - Geschäftsführer: Andreas Muchow

**Pull request merged**
