### PR TITLE
Add an option to set Geshi path

### PR DESCRIPTION
**Pull request by Tom-H-**
Add an option to set Geshi path.
May be useful when using a package manager.

### CODE REVIEW

**Comment by michael-o** [comment]
We have removed this in the previous release and require it to be installed via pear. I am reluctant to reintroduce it.

**Comment by michael-o** [comment]
@ams-tschoening, true we never had a configurable path. We simply removed it and relied on PEAR.

I also would like to see the benefit of.

**Comment by michael-o** [comment]
When one uses PEAR he doesn't care about the path, it simply works. That is why rely on PEAR now.
Geshi isn't a binary, it is a PHP library and for that PEAR makes totally sense.

**Comment by ams-tschoening** [comment]
I'm with @michael-o on this, Gehi is not a binary and needs to be dealt differently. Geshi is a lib and PHP has a concept of including those either by absolute path, which is what you are using in the PR, or by relative names according to some pre-configured include paths. Your current approach would force us to add some config for each new PHP lib used, while it would work automatically by simply preferring PEAR, because that provides the include paths so that things work automatically.

While I do prefer APT to custom packagers in general, other runtimes like Perl seem to be better integrated with APT: If I install some Perl lib using APT, it is automatically stored in a place which is in the include paths of Perl by default, so things simply work. This doesn't seem to be the case for at least Geshi or even PHP in general.

So what we would really need would be 1 config to add paths to the PHP include paths in general and in your example, after installing Geshi using APT one would add the path used by APT in that config afterwards. For now I don't see significant benefit of adding such a config and therefore vote for that we don't merge this PR and instead rely on PEAR being used by default for the time being.

http://php.net/manual/en/ini.core.php#ini.include-path
http://php.net/manual/en/function.require.php

**Comment by michael-o** [comment]
> While I do prefer APT to custom packagers in general, other runtimes like Perl seem to be better integrated with APT: If I install some Perl lib using APT, it is automatically stored in a place which is in the include paths of Perl by default, so things simply work. This doesn't seem to be the case for at least Geshi or even PHP in general.

Exactly, this is how I use it with the FreeBSD ports system, install PEAR via ports and then install Geshi via ports => PEAR. It just works.

**Pull request closed without merging**
