### PR TITLE
Improve mobile browsing with "calm" template

### PR DESCRIPTION
**Pull request by Badatos**
add "viewport" meta tag + some CSS media queries

See https://github.com/websvnphp/websvn/issues/91 for the discussion start

### CODE REVIEW

**Comment by ams-tschoening** [comment]
You should try to avoid massively reformatting the code. While e.g. spaces vs. tabs can be ignored by manually applying patches most likely, it's more difficult during merging PRs, especially here.

**Comment by Badatos** [comment]
Ok. Do you prefer I make the code uniformization in a different commit ?

**Comment by ams-tschoening** [comment]
I would have preferred you wouldn't have started this topic at all. ;-) The problem was tabs vs. spaces in your CSS-file, so you changed to spaces. All other CSS-files seemed to have used tabs instead already, like the PHP files. So I 1. added some `.editorconfig` to document those cases as somewhat official style guide and 2. changed your file to get in line with that style as well.

You should now have consistent tabs vs. spaces and shouldn't need to care about uniformization at all anymore. Just stay with the tabs.

Besides that I suggest you don't comment individual CSS-rules you don't need anymore, but really remove them. Commented lines only blow the file and without any additional docs nobody knows why they have been commented once anyway. If one needs to look at the GIT history already, there's not much difference between commented and removed lines in my opinion.

**Comment by Badatos** [comment]
Thanks for the changes and the code guidelines.
I resolved conflicts according to them, and deleted commented lines in css as you rightly suggested. I think the PR can be merged now without problem.

**Comment by michael-o** [comment]
@ams-tschoening Can you review it again? I'd like to cut 2.5.1 after this.

**Comment by michael-o** [comment]
@Badatos, can you please squash your work?

**Comment by ams-tschoening** [comment]
I don't have the time currently to look into this more detailed, but what I've seen looked OK.

@Badatos I suggest you create an individual branch to base your PR on next time instead of using your master. Makes it easier for you to move forward and apply changes as requested for the PR only without losing anything of interest to you.

**Comment by Badatos** [comment]
@michael-o What do you mean by "squashing" my work ?
@ams-tschoening thanks for the advice. I will do in future PR. For this one, All i've done in this master is for the same PR. You can just merge the entire branch.

**Comment by michael-o** [comment]
@Badatos have a look [here](https://lmgtfy.com/?q=git+squash+commits).

**Comment by Badatos** [comment]
Sorry, but I didn't find any "squash" button on github.com, neither in github Desktop App. And Google is not helping...

**Comment by Badatos** [comment]
I finally found the "squash" button ! but it"s not up to me, only You can click on it !!
see here : https://help.github.com/en/articles/merging-a-pull-request
You just have to click on "squash and merge" instead of only "Merge Pull Request"
Maybe you can use Google to find more how it works.

**Comment by Badatos** [comment]
Hello !
It's me again ;)
Have you found the "squash and merge" button to merge this PR ?

**Comment by michael-o** [comment]
You where requested to do so.

**Comment by Badatos** [comment]
Sorry, but there is no easy way for me to do that, whereas you can do it in just one click on the "squash and merge" button.

**Comment by michael-o** [comment]
I cannot not, GitHub says: This branch cannot be rebased due to conflicts.

Terminal:
```
$ git rebase -i HEAD~5
... do fixup
$ git rebase master
$ git push --force
```

That's why I don't use GUI tools this, people -- most of the time -- don't know what they do.

**Comment by ams-tschoening** [comment]
Done, results look OK. I've additionally renamed the corresponding issue and made clear in the commit message that and why we focus on `calm` for now.

@Badatos For further improvements I suggest using a distinct branch for `calm`-related changes only and to create new PRs if you collected enough changes worth merging. We'll then simply repeat that game once in a while. :-) Other templates/skins, other branches, other PRs or stuff like that.

Thanks for contributing!

**Comment by Badatos** [comment]
Thanks @ams-tschoening !
Sorry for the work in "master". I will make further changes in a separate branch.
Have a nice day !

**Pull request merged**
