### PR TITLE
Add an option to ignore files outside of subpath in logs

### PR DESCRIPTION
**Pull request by Tom-H-**
Add an option to ignore files outside of subpath in logs instead of showing an error ("Log entries do not start with subpath for repository with subpath").

### CODE REVIEW

**Comment by michael-o** [comment]
Can you tell when this happens in real world? I don't have a case for this from the top of my head.

**Comment by ams-tschoening** [comment]
> The current behavior of WebSVN when it encounters this case is to break and throws an error.
> I propose to add an option to just ignore/hide files outside subpath in the logs.

Did you try what happens without subpath checking etc. at all? Because from my understanding SVNs default behaviour is already not showing any data one doesn't has any access to:

> Q: How does svnsync deal with parts of the master repository that I'm not
   authorized to read?

> A: svnsync will simply not copy parts of the repository that you
   cannot read; files copied from "private" parts of the repository
   into "public" parts will look as if they have been added from
   scratch.  **If a revision only modifies files that you cannot read,
   it will appear to be empty.  (Just like with "svn log", log
   messages from revisions you cannot read part of will be empty.)**

**Comment by Tom-H-** [comment]
If you mean to use `$config->addRepository('NameToDisplay', 'localURL/subpath');` instead of `$config->addRepositorySubpath('NameToDisplay', 'localURL', 'subpath');`, yes but file paths are just broken (the SVN server root is used instead of subpath). I guess the goal of addRepositorySubpath is to solve this problem.

If you mean to disallow siblings folder with access rights, it's works (after some debug #68). But the performances are just insane, it's 10x slower (0.75s --> 6.5s to generate the RSS flux).

I think the real question is: How do you expect WebSVN to react to this case? And I think that ignoring the file is a good option.

Now, is it necessary to add it as an option, or is it more relevant that it becomes the default behavior?

**Comment by michael-o** [comment]
@Tom-H- Seriously, relying on `authz` file is way slower than this PR? Which Subversion version did you try?

**Comment by ams-tschoening** [comment]
@michael-o Remember that we changed to use `svnauthz`. So depending on how RSS is generated in his use case actually, it might result in an excessive amount of invocation of that app leading to that slowdown?

@Tom-H- I meant access rights and simply had forgotten that the subpath-thing is a WebSVN-concept.
 
If we want to stick with the subpath-concept, I vote for getting rid of the config entirely and change the default behaviour to simply ignore what is not in the subpath. This way we get in line how I understand SVN behaves anyway, get rid of configs needed to document, of error messages which would need to be recognized in templates, translated in theory etc. Seems to make everything easier to me and can be merged using this PR.

Using permissions only seems to be the proper approach in future to me and should replace the subpath-handling by WebSVN, unless that has an additional use case not covered by permissions. Might that use case be easier config already? But as you already found the performance issue anyway, I suggest you file another bug for that performance problem and one enhancement about discussing removing the subpath-concept linking here and to the performance problem. Both seem two become different topics than this PR now.

**Comment by michael-o** [comment]
> @michael-o Remember that we changed to use svnauthz. So depending on how RSS is generated in his use case actually, it might result in an excessive amount of invocation of that app leading to that slowdown?

I agree, this needs to be investigated. Though, I'd like to see some evidence by @Tom-H- for this. Using `svnauthz(1)` still seems to me to be the right thing to do.

I also fully agree with the rest you have written.

**Pull request merged**
