### PR TITLE
Fix highlighted diffs of files starting with newlines

### PR DESCRIPTION
**Pull request by LordAro**
I've been seeing issues where the highlighted diff line actually has no differences, and the line that's actually changed is slightly further up:

image
(`CreateObj` -> `CreateNodeObj`)

After lots of printf debugging, I've been able to narrow the issue down to the handling of highlighted files, and a `trim()` statement (there are so many intermediate files used here!).

Because enscript doesn't actually produce any output containing `<br />` tags, the `explode("<br />")` does nothing, meaning that `$content` is an array of 1 big element. Running trim() on that removes the leading (and trailing) newlines and causes the diff output to be incorrect.

I'll be honest, I don't properly understand this code and what it's supposed to be doing. I don't know why the code is expecting html-encoded text. Is that something GeSHi does? I'm not using that (and it's not pulled in by composer, should it be?), so it's difficult to be sure.

After:
image

Furthermore, enscript doesn't appear to be doing any text highlighting at all - it's seemingly only escaping some html chars.

### CODE REVIEW

**Comment by michael-o** [comment]
That's an interesting one. Will look at this this week.

**Comment by ams-tschoening** [comment]
Is that related to the following reported issue using a system wide `diff` instead of `Text_Diff`?

https://github.com/websvnphp/websvn/issues/130

**Comment by LordAro** [comment]
I suppose it's plausibly related, but I'm definitely using `Text_Diff`/`inline_diff`

I have no issue with the "diff output" (I tried both to be sure), it's how the `enscript` output is handled

**Comment by ams-tschoening** [comment]
Makes sense, would be great if you could take the time to test your changes with GESHI as well. Regarding the code, it would totally make sense that with/without GESHI input is simply different, HTML-encoded vs. not.

```
if ($highlight != 'no' && $config->useGeshi && $geshiLang = $this->highlightLanguageUsingGeshi($path)) {
	$this->applyGeshi($path, $tempname, $geshiLang, $rev, $peg);
} else if ($highlight != 'no' && $config->useEnscript) {
	// Get the files, feed it through enscript, then remove the enscript headers using sed
	// Note that the sed command returns only the part of the file between <PRE> and </PRE>.
	// It's complicated because it's designed not to return those lines themselves.
	$cmd = $this->svnCommandString('cat', $path, $rev, $peg);
	$cmd = $cmd.' | '.$this->enscriptCommandString($path).' | '.
	$config->sed.' -n '.$config->quote.'1,/^<PRE.$/!{/^<\\/PRE.$/,/^<PRE.$/!p;}'.$config->quote.' > '.$tempname;
} else {
	$highlighted = false;
	$cmd = $this->svnCommandString('cat', $path, $rev, $peg);
	$cmd = $cmd.' > '.quote($filename);
}
```

https://github.com/websvnphp/websvn/blob/fb2a2ca1a4fb1796025d4ab84b65fd308e3ed757/include/svnlook.php#L684

**Comment by michael-o** [comment]
Does anyone use enscript at all? Should we remove it?

**Comment by michael-o** [comment]
Your patch makes sense. It is quite weird that the spilt happens on `<br>` but the join on `\n`.

**Comment by LordAro** [comment]
Other than me? :p I use it because, at the time, it was the cleaner solution (install thing via apt) than installing random non-apt PHP packages. If GESHI is added to the composer file, I'll happily use it instead

**Comment by michael-o** [comment]
It is, composer-based installation just works.

**Comment by LordAro** [comment]
So it does. Could've sworn I tried it and it didn't work

And to confirm - yes, GESHI returns html-based highlighted text, which is clearly where this problem comes from. Just in case you want to keep enscript, I'll amend the PR

**Comment by michael-o** [comment]
Regarding composer see my comments in the appropriate PR. It worked for me, it should for you too.

**Review by michael-o — APPROVED** [review]

**Review by ams-tschoening — APPROVED** [review]

**Pull request merged**
